#!/usr/bin/env bash
#
# Generates the per symbol artifact set the results site's selector switches
# between, from the full day NASDAQ capture.
#
# This cannot run in CI and is not meant to. The capture is 7.68 GB, lives on one
# machine, and is gitignored, so what lands in the repository is the derived JSON
# and a provenance block naming the input, its hash, and the command line. The
# guarded set is QQQ on the committed slice; see scripts/generate_ci_artifacts.sh.
#
# Why it extracts first. Running the strategy sweeps directly against the full
# capture would mean twenty five passes over 7.68 GB per symbol. Extracting the
# symbol once into a slice, then running everything against the slice, is the same
# arithmetic on the same bytes for a fraction of the reading. The extraction step
# writes its own provenance to source.json, so the chain from the original capture
# to every number is recorded rather than assumed.
#
# Usage:
#   scripts/generate_symbol_artifacts.sh <capture> <symbol> [symbol...]
#
# Environment:
#   OB_BIN      directory holding the built tools, default out/build/gcc-release
#   OB_OUT      artifact root, default site/data/symbols
#   OB_SLICES   where extracted slices are kept, default data/slices
#   OB_REUSE    set to 1 to reuse an existing slice rather than re-extracting

set -euo pipefail

cd "$(dirname "$0")/.."

if [[ $# -lt 2 ]]; then
  echo "usage: $0 <capture> <symbol> [symbol...]" >&2
  exit 2
fi

CAPTURE="$1"
shift

OB_BIN="${OB_BIN:-out/build/gcc-release}"
OB_OUT="${OB_OUT:-site/data/symbols}"
OB_SLICES="${OB_SLICES:-data/slices}"
OB_REUSE="${OB_REUSE:-0}"

resolve() {
  local name="$1"
  if [[ -x "${OB_BIN}/${name}" ]]; then
    printf '%s/%s' "${OB_BIN}" "${name}"
  elif [[ -x "${OB_BIN}/${name}.exe" ]]; then
    printf '%s/%s.exe' "${OB_BIN}" "${name}"
  else
    echo "cannot find ${name} in ${OB_BIN}" >&2
    exit 1
  fi
}

REPLAY="$(resolve itch_replay)"
BACKTEST="$(resolve ob_strategy_backtest)"

if [[ ! -f "${CAPTURE}" ]]; then
  echo "missing capture ${CAPTURE}" >&2
  exit 1
fi

echo "hashing ${CAPTURE}, which takes a while at this size"
CAPTURE_SHA="$(sha256sum "${CAPTURE}" | cut -d' ' -f1)"
CAPTURE_BYTES="$(wc -c <"${CAPTURE}" | tr -d ' ')"
echo "capture sha256 ${CAPTURE_SHA}"

mkdir -p "${OB_SLICES}"

for SYMBOL in "$@"; do
  echo
  echo "=== ${SYMBOL} ==="

  SLICE="${OB_SLICES}/${SYMBOL}.itch"
  EXTRACT_COMMAND="itch_replay --symbol ${SYMBOL} --extract ${SLICE} ${CAPTURE}"

  if [[ "${OB_REUSE}" == "1" && -f "${SLICE}" ]]; then
    echo "reusing ${SLICE}"
  else
    echo "extracting ${SYMBOL} from the full capture"
    "${REPLAY}" --symbol "${SYMBOL}" --extract "${SLICE}" "${CAPTURE}" | tail -1
  fi

  SLICE_SHA="$(sha256sum "${SLICE}" | cut -d' ' -f1)"
  SLICE_BYTES="$(wc -c <"${SLICE}" | tr -d ' ')"

  DIR="${OB_OUT}/${SYMBOL}"
  mkdir -p "${DIR}"

  # The chain from the original capture to the slice every artifact names. Written
  # by hand rather than by a tool because no tool sees both ends of it.
  cat >"${DIR}/source.json" <<JSON
{
  "schema": 1,
  "symbol": "${SYMBOL}",
  "capture": "${CAPTURE}",
  "capture_bytes": ${CAPTURE_BYTES},
  "capture_sha256": "${CAPTURE_SHA}",
  "extract_command": "${EXTRACT_COMMAND}",
  "slice": "${SLICE}",
  "slice_bytes": ${SLICE_BYTES},
  "slice_sha256": "${SLICE_SHA}",
  "reproducible_in_ci": false,
  "note": "The capture is gitignored at 7.68 GB, so this symbol's numbers cannot be regenerated by a runner. Only QQQ on the committed slice is guarded; see site/data/SCHEMA.md."
}
JSON

  echo "replay and depth"
  "${REPLAY}" \
    --symbol "${SYMBOL}" \
    --json "${DIR}/replay.json" \
    --json-depth "${DIR}/depth.json" \
    --sha256 "${SLICE_SHA}" \
    "${SLICE}" >/dev/null

  echo "backtest baseline"
  "${BACKTEST}" \
    --file "${SLICE}" \
    --symbol "${SYMBOL}" \
    --json "${DIR}/backtest.json" \
    --sha256 "${SLICE_SHA}" >/dev/null

  echo "parameter and latency sweeps, twenty five replays"
  "${BACKTEST}" \
    --file "${SLICE}" \
    --symbol "${SYMBOL}" \
    --sweep \
    --latency-sweep \
    --json "${DIR}/sweeps.json" \
    --sha256 "${SLICE_SHA}" >/dev/null

  echo "${SYMBOL} done"
done

echo
echo "now run scripts/build_index.py to rebuild site/data/index.json"
